import { Address, Appointment, Customer } from "@prisma/client";

const customers: Customer[] = [
  {
    id: "ckpyetj5z0000i1mhfouaq40z",
    firstName: "John",
    lastName: "Doe",
    contact: "john.doe@example.com",
    suspended: false,
    suspendedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "ckpyetj5z0001i1mhm3tvbhel",
    firstName: "Jane",
    lastName: "Smith",
    contact: "jane.smith@example.com",
    suspended: false,
    suspendedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "ckpyetj5z0002i1mhmhbyon5r",
    firstName: "Bob",
    lastName: "Johnson",
    contact: "bob.johnson@example.com",
    suspended: false,
    suspendedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "ckpyetj5z0003i1mhmraqqbj2",
    firstName: "Alice",
    lastName: "Williams",
    contact: "alice.williams@example.com",
    suspended: false,
    suspendedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "ckpyetj5z0004i1mhmz5craju",
    firstName: "Charlie",
    lastName: "Brown",
    contact: "charlie.brown@example.com",
    suspended: true,
    suspendedAt: new Date(), // Marked as suspended
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "ckpyetj5z0005i1mhn6s4gyvh",
    firstName: "Eva",
    lastName: "Davis",
    contact: "eva.davis@example.com",
    suspended: true,
    suspendedAt: new Date(), // Marked as suspended
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "ckpyetj5z0006i1mhncafsdt2",
    firstName: "Frank",
    lastName: "Miller",
    contact: "frank.miller@example.com",
    suspended: false,
    suspendedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "ckpyetj5z0007i1mhnkx8fcu7",
    firstName: "Grace",
    lastName: "Wilson",
    contact: "grace.wilson@example.com",
    suspended: false,
    suspendedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "ckpyetj5z0008i1mhnq5qat8y",
    firstName: "Henry",
    lastName: "Thomas",
    contact: "henry.thomas@example.com",
    suspended: false,
    suspendedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "ckpyetj5z0009i1mhnwq5mn8v",
    firstName: "Ivy",
    lastName: "Moore",
    contact: "ivy.moore@example.com",
    suspended: false,
    suspendedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
const addresses: Address[] = [
  {
    id: "ckpyetj6z0000i1mh3fdw4vps",
    customerId: "ckpyetj5z0000i1mhfouaq40z",
    number: "123",
    line1: "Main Street",
    line2: "Apt 4",
    suburb: "Cityville",
    createdAt: generateRandomDate(),
    updatedAt: new Date(),
  },
  {
    id: "ckpyetj6z0001i1mh06m90gvm",
    customerId: "ckpyetj5z0001i1mhm3tvbhel",
    number: "456",
    line1: "Oak Avenue",
    line2: "",
    suburb: "Suburbia",
    createdAt: generateRandomDate(),
    updatedAt: new Date(),
  },
  {
    id: "ckpyetj6z0002i1mhwj8cskst",
    customerId: "ckpyetj5z0002i1mhmhbyon5r",
    number: "789",
    line1: "Pine Street",
    line2: "Suite 10",
    suburb: "Townsville",
    createdAt: generateRandomDate(),
    updatedAt: new Date(),
  },
  {
    id: "ckpyetj6z0003i1mh3cn2g3m0",
    customerId: "ckpyetj5z0003i1mhmraqqbj2",
    number: "1011",
    line1: "Cedar Road",
    line2: "",
    suburb: "Villageland",
    createdAt: generateRandomDate(),
    updatedAt: new Date(),
  },
  {
    id: "ckpyetj6z0004i1mh5nwmb2r4",
    customerId: "ckpyetj5z0004i1mhmz5craju",
    number: "1213",
    line1: "Maple Lane",
    line2: "Unit 7",
    suburb: "Hamlet City",
    createdAt: generateRandomDate(),
    updatedAt: new Date(),
  },
  {
    id: "ckpyetj6z0005i1mhrft0wt3q",
    customerId: "ckpyetj5z0005i1mhn6s4gyvh",
    number: "1415",
    line1: "Birch Avenue",
    line2: "",
    suburb: "Countryside",
    createdAt: generateRandomDate(),
    updatedAt: new Date(),
  },
  {
    id: "ckpyetj6z0006i1mhw3mvsjk1",
    customerId: "ckpyetj5z0006i1mhncafsdt2",
    number: "1617",
    line1: "Spruce Street",
    line2: "Apt 3",
    suburb: "Meadowland",
    createdAt: generateRandomDate(),
    updatedAt: new Date(),
  },
  {
    id: "ckpyetj6z0007i1mhj1ej4cw4",
    customerId: "ckpyetj5z0007i1mhnkx8fcu7",
    number: "1819",
    line1: "Redwood Road",
    line2: "",
    suburb: "Hometown",
    createdAt: generateRandomDate(),
    updatedAt: new Date(),
  },
  {
    id: "ckpyetj6z0008i1mhphkmg95t",
    customerId: "ckpyetj5z0008i1mhnq5qat8y",
    number: "2021",
    line1: "Fir Lane",
    line2: "Suite 5",
    suburb: "Greenfield",
    createdAt: generateRandomDate(),
    updatedAt: new Date(),
  },
  {
    id: "ckpyetj6z0009i1mhrzjsjs2w",
    customerId: "ckpyetj5z0009i1mhnwq5mn8v",
    number: "2223",
    line1: "Holly Street",
    line2: "",
    suburb: "Cottageville",
    createdAt: generateRandomDate(),
    updatedAt: new Date(),
  },
];
const appointments: Appointment[] = [
  {
    id: "ckpyetj6z0000i1mhfouaq40z",
    customerId: "ckpyetj5z0000i1mhfouaq40z",
    recurring: false,
    frequency: null,
    customerIsOwner: false,
    addressId: "ckpyetj6z0000i1mh3fdw4vps",
    start: "2023-10-31T10:00:00Z",
    end: "2023-10-31T11:00:00Z",
    completed: false,
    createdAt: generateRandomDate(),
    updatedAt: new Date(),
  },
  {
    id: "ckpyetj6z0001i1mhm3tvbhel",
    customerId: "ckpyetj5z0001i1mhm3tvbhel",
    recurring: true,
    frequency: 7,
    customerIsOwner: false,
    addressId: "ckpyetj6z0001i1mh06m90gvm",
    start: "2023-11-01T14:00:00Z",
    end: "2023-11-01T15:00:00Z",
    completed: false,
    createdAt: generateRandomDate(),
    updatedAt: new Date(),
  },
  {
    id: "ckpyetj6z0002i1mhmhbyon5r",
    customerId: "ckpyetj5z0002i1mhmhbyon5r",
    recurring: false,
    frequency: null,
    customerIsOwner: false,
    addressId: "ckpyetj6z0002i1mhwj8cskst",
    start: "2023-11-02T09:00:00Z",
    end: "2023-11-02T10:00:00Z",
    completed: false,
    createdAt: generateRandomDate(),
    updatedAt: new Date(),
  },
  {
    id: "ckpyetj6z0003i1mhmraqqbj2",
    customerId: "ckpyetj5z0003i1mhmraqqbj2",
    recurring: false,
    frequency: null,
    customerIsOwner: false,
    addressId: "ckpyetj6z0003i1mh3cn2g3m0",
    start: "2023-11-03T15:30:00Z",
    end: "2023-11-03T16:30:00Z",
    completed: false,
    createdAt: generateRandomDate(),
    updatedAt: new Date(),
  },
  {
    id: "ckpyetj6z0004i1mhmz5craju",
    customerId: "ckpyetj5z0004i1mhmz5craju",
    recurring: false,
    frequency: null,
    customerIsOwner: false,
    addressId: "ckpyetj6z0004i1mh5nwmb2r4",
    start: "2023-11-04T12:00:00Z",
    end: "2023-11-04T13:00:00Z",
    completed: false,
    createdAt: generateRandomDate(),
    updatedAt: new Date(),
  },
  {
    id: "ckpyetj6z0005i1mhn6s4gyvh",
    customerId: "ckpyetj5z0005i1mhn6s4gyvh",
    recurring: false,
    frequency: null,
    customerIsOwner: false,
    addressId: "ckpyetj6z0005i1mhrft0wt3q",
    start: "2023-11-05T11:00:00Z",
    end: "2023-11-05T12:00:00Z",
    completed: false,
    createdAt: generateRandomDate(),
    updatedAt: new Date(),
  },
];

/**
 * Generates a random date within the range of 1 to 7 days ago from the current date.
 *
 * @returns A random date within the specified range.
 */
function generateRandomDate(): Date {
  const currentDate = new Date();
  const randomDifference = Math.floor(Math.random() * 7 + 1);
  const newDate = new Date(currentDate);
  newDate.setDate(currentDate.getDate() - randomDifference);
  return newDate;
}

export { customers, addresses, appointments };
